### ISSUE TITLE
partition cluster: dashboard error when deallocating nodes

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#141]
**Software:*** r3
feda38f

**Component:** Partition cluster
**Hardware:**node003 poweredge
**Test case:**2.1.3
**Bug description:**
From dashboard there is an error when trying to deallocate nodes
**Steps to reproduce:**
- log into openstack dashboard with admin credentials
- click on edit cluster a
- remove a node from the cluster

**Expected output:**
successful deallocation

**Actual output:**
"Danger: There was an error submitting the form. Please try again"

**Comment by themisa** [comment]
Output from /var/log/trinity/trinity_api.log:

Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python2.7/site-packages/trinity_api/api.py", line 629, in modify_cluster
    for cont in adds_list+subs_list:
NameError: global name 'adds_list' is not defined
10.141.0.3 - - [26/Mar/2015 11:17:08] "PUT /trinity/v1/clusters/a HTTP/1.1" 500 1367

**Comment by themisa** [comment]
fixed in * r3
c5a68e5
