### ISSUE TITLE
Obol: adding a user to a group after they are created does not work

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#154]
Adding a user to a group after they are created doesn't work:
[root@login ~]# obol group addusers power-users themis
themis 1053
{'info': 'modify/add: memberUid: value #0 already exists', 'desc': 'Type or value exists'}
Traceback (most recent call last):
File "/usr/sbin/obol", line 290, in 
fun(args_d)
File "/usr/sbin/obol", line 162, in group_addusers
conn.modify_s(dn, mod_attrs)
File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 357, in modify_s
return self.result(msgid,all=1,timeout=self.timeout)
File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 458, in result
resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 462, in result2
resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 469, in result3
resp_ctrl_classes=resp_ctrl_classes
File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 476, in result4
ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
result = func(*args,kwargs)
ldap.TYPE_OR_VALUE_EXISTS: {'info': 'modify/add: memberUid: value #0 already exists', 'desc': 'Type or value exists'}

**Comment by hansthen** [comment]
This is probably because the user is already a member of that group. @themisa Can you verify this using the command?
obol group show power-users

**Comment by hansthen** [comment]
I will ensure a better error message (or silence this specific error message).

**Comment by themisa** [comment]
root@login home]# obol user show john
{'uid': ['john'], 'objectClass': ['top', 'person', 'organizationalPerson', 'inetOrgPerson', 'posixAccount', 'shadowAccount'], 'loginShell': ['/bin/bash'], 'userPassword': ['123'], 'uidNumber': ['1050'], 'gidNumber': ['1050'], 'sn': ['Smith'], 'homeDirectory': ['/home/john'], 'givenName': ['John'], 'cn': ['John']}
[root@login home]# obol group addusers power-users john

root@login home]# obol group show power-users
{'objectClass': ['top', 'posixGroup'], 'memberUid': ['jane', 'john'], 'gidNumber': ['151'], 'cn': ['power-users']}

Works in * r3
78f4bc5
