### ISSUE TITLE
cv_install_moncon: monitoring installation error

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#198]
**Software:** trinity v. * r3
9f5a966

**Component:** monitoring: cv_install_moncon
**Hardware:** controller02, SM
**Test case:**
**Bug description:**
when running cv_install_moncon, there are errors. 
**Steps to reproduce:**
ssh controller02
sh /xcatpost/cv_install_moncon
**Expected output:**
**Actual output:**
```
[root@controller xcatpost]# ./cv_install_moncon
Traceback (most recent call last):
  File "./cv_install_moncon", line 125, in <module>
    main(default_xcat_host,default_xcat_query,default_monitoring,default_hosts_file,default_aggr_file)
  File "./cv_install_moncon", line 113, in main
    hosts_dict=mc.get_hosts_from_xcat()
  File "./cv_install_moncon", line 29, in get_hosts_from_xcat
    node_list=requests.get("https://"+self.xcat_host+"/xcatws"+"/nodes", verify=False, params=self.xcat_query).json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 604, in json
    return json.loads(self.text or self.content)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by themisa** [comment]
first need to run cv_install_xcat_ws
also trinity_api restart
