### ISSUE TITLE
obol: issues with creating user

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#415]
**Version:** r5_fixes 17e6458
**Environment:** amaster

Report from clusterbats

```
1..4
ok 1 Can reach the virtual login node
not ok 2 Create a user for the login node
# (in test file /trinity/testing/clusterbats/run_mpi.bats, line 9)
#   `sshpass -p system ssh login.vc-a "' failed
# Warning: Permanently added 'login.vc-a,172.16.255.254' (ECDSA) to the list of known hosts.
# {'desc': 'No such object'}
# Traceback (most recent call last):
#   File "/usr/sbin/obol", line 308, in <module>
#     fun(**args_d)
#   File "/usr/sbin/obol", line 32, in user_add
#     uidNumber = increment_uid()
#   File "/usr/lib/python2.7/site-packages/retrying.py", line 68, in wrapped_f
#     return Retrying(*dargs, **dkw).call(f, *args, **kw)
#   File "/usr/lib/python2.7/site-packages/retrying.py", line 229, in call
#     raise attempt.get()
#   File "/usr/lib/python2.7/site-packages/retrying.py", line 261, in get
#     six.reraise(self.value[0], self.value[1], self.value[2])
#   File "/usr/lib/python2.7/site-packages/retrying.py", line 217, in call
#     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
#   File "/usr/sbin/obol", line 197, in increment_uid
#     result = conn.search_s( dn, ldap.SCOPE_SUBTREE, filter, attrs)
#   File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 552, in search_s
#     return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
#   File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 546, in search_ext_s
#     return self.result(msgid,all=1,timeout=timeout)[1]
#   File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 458, in result
#     resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)
#   File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 462, in result2
#     resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)
#   File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 469, in result3
#     resp_ctrl_classes=resp_ctrl_classes
#   File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 476, in result4
#     ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
#   File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
#     result = func(*args,**kwargs)
# ldap.NO_SUCH_OBJECT: {'desc': 'No such object'}
```

**Comment by hansthen** [comment]
This is related to #406. I will do a quick fix now, but I want the login node to (somehow) use the same postscripts as the other xcat nodes.
