### ISSUE TITLE
rebooting controller: trinity_api also needed rebooting

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#557]
**Version:** r6 70e2fb1
**Environment:** tmaster

After a reboot of the controller, it was not possible to access the "HPC" page of the dashboard, until after a service trinity_api restart

**Comment by themisa** [comment]
[root@controller(tmaster) ~]# service trinity_api status
Not Running.

after a reboot

**Comment by themisa** [comment]
**Version:** r7 85ff0e9
**Environment:** dmaster

still an issue

[root@controller(dmaster) ~]# service trinity_api status
Not Running.

**Comment by hansthen** [comment]
Can you add the contents of the trinity_api log and/or /var/log/messages.

**Comment by themisa** [comment]
```
[root@controller(dmaster) ~]# cat /var/log/trinity/trinity_api.log 
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/bin/trinity_api", line 6, in <module>
    api.startup()
  File "/usr/lib/python2.7/site-packages/trinity_api/api.py", line 1119, in startup
    xcat_networks=requests.get(xcat_host+path,verify=False,params=query,headers=headers).json()["networks"]
KeyError: 'networks'
```

**Comment by hansthen** [comment]
There is a dependency on xCAT for the trinity api to be started.

**Comment by themisa** [comment]
Fixed after reboot:

[root@controller ~(keystone_a)]# /trinity/report
**Version:** r7 b55e0e1
**Environment:** tmaster

```
[root@controller ~(keystone_a)]# service trinity_api status
6514
Running.
[root@controller ~(keystone_a)]# systemctl status trinity_api 
● trinity_api.service - LSB: Trinity API server
   Loaded: loaded (/etc/rc.d/init.d/trinity_api)
   Active: active (running) since Wed 2016-01-20 12:39:16 UTC; 46min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 6504 ExecStart=/etc/rc.d/init.d/trinity_api start (code=exited, status=0/SUCCESS)
   Memory: 19.0M
   CGroup: /system.slice/trinity_api.service
           6514 /usr/bin/python /usr/bin/trinity_api

Jan 20 12:39:14 controller.cluster systemd[1]: Starting LSB: Trinity API server...
Jan 20 12:39:16 controller.cluster trinity_api[6504]: Starting trinity_api:[  OK  ]
Jan 20 12:39:16 controller.cluster systemd[1]: Started LSB: Trinity API server.
```
