### ISSUE TITLE
r7_login_image: errors running cv_install_moncon

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#584]
**Version:** r7_login_image 14a418e
**Environment:** dmaster

When trying to install cv_install_moncon, there are errors and the installation cannot proceed:

```
[root@controller xcatpost(keystone_new)]# ./cv_install_moncon 
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[u'node001', u'node002', u'node003', u'node004']
node001,node002,node003,node004
Traceback (most recent call last):
  File "./cv_install_moncon", line 116, in <module>
    main(default_xcat_host,default_xcat_query,default_monitoring,default_hosts_file,default_aggr_file)
  File "./cv_install_moncon", line 106, in main
    mc.add_hosts(hosts_dict)
  File "./cv_install_moncon", line 63, in add_hosts
    self.add_host(host_name,host_ip)
AttributeError: 'MonCon' object has no attribute 'add_host'
```

**Comment by themisa** [comment]
Fixed in

**Version:** r7_login_image 660733d
**Environment:** tmaster


installation of moncon proceeds

```
[root@controller(tmaster) xcatpost]# ./cv_install_moncon 
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
[u'node001', u'node002']
node001,node002
ALL HOSTS: Added host node001
Generating configuration for core (type nagios)...OK
Validating Nagios configuration...OK
Precompiling host checks...OK
```
