### ISSUE TITLE
cannot log into new login node via hostname (only via ip)

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#588]
[root@controller ~(keystone_new)]# /trinity/report
**Version:** r7_login_image 660733d
**Environment:** tmaster

```
[root@controller ~(keystone_new)]# nova list
+--------------------------------------+-----------+--------+------------+-------------+------------------------------------------+
| ID                                   | Name      | Status | Task State | Power State | Networks                                 |
+--------------------------------------+-----------+--------+------------+-------------+------------------------------------------+
| 7f1e2455-8a57-41b4-adb9-a480cf3f08df | login-new | ACTIVE | -          | Running     | novanetwork=192.168.32.3, 172.17.255.254 |
+--------------------------------------+-----------+--------+------------+-------------+------------------------------------------+
[root@controller ~(keystone_new)]# ssh login.vc-new
ssh: Could not resolve hostname login.vc-new: Name or service not known
[root@controller ~(keystone_new)]# ssh login-new
ssh: Could not resolve hostname login-new: Name or service not known
```

From trinity_api.log:
```
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Bottle v0.12.9 server starting up (using CherryPyServer())...
Listening on http://10.141.255.254:32123/
Hit Ctrl-C to quit.

PING 172.16.255.254 (172.16.255.254) 56(84) bytes of data.
64 bytes from 172.16.255.254: icmp_seq=1 ttl=64 time=0.284 ms

--- 172.16.255.254 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.284/0.284/0.284/0.000 ms
uid=1002(munge) gid=1002(munge) groups=1002(munge)
1024+0 records in
1024+0 records out
1024 bytes (1.0 kB) copied, 0.00638098 s, 160 kB/s
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python2.7/site-packages/trinity_api/api.py", line 650, in modify_cluster
    cpu_count=all_nodes_info[cont]['cpucount']
KeyError: 'cpucount'
PING 172.17.255.254 (172.17.255.254) 56(84) bytes of data.
From 10.141.255.254 icmp_seq=1 Destination Host Unreachable

--- 172.17.255.254 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

But can login via ip:
```
root@controller ~(keystone_new)]# ssh 172.17.255.254
Warning: Permanently added '172.17.255.254' (ECDSA) to the list of known hosts.
root@172.17.255.254's password: 
[root@login ~]# 
From nova console-log:
```

```
login login: [   19.512217] cloud-init[766]: Cloud-init v. 0.7.5 running 'init' at Thu, 14 Jan 2016 10:40:13 +0000. Up 19.21 seconds.
[   19.696526] cloud-init[766]: ci-info: ++++++++++++++++++++++++++Net device info+++++++++++++++++++++++++++
[   19.699645] cloud-init[766]: ci-info: +--------+------+--------------+---------------+-------------------+
[   19.702616] cloud-init[766]: ci-info: | Device |  Up  |   Address    |      Mask     |     Hw-Address    |
[   19.718915] cloud-init[766]: ci-info: +--------+------+--------------+---------------+-------------------+
[   19.721913] cloud-init[766]: ci-info: |  lo:   | True |  127.0.0.1   |   255.0.0.0   |         .         |
[   19.724841] cloud-init[766]: ci-info: | eth0:  | True | 192.168.32.3 | 255.255.255.0 | fa:16:3e:71:56:13 |
[   19.727772] cloud-init[766]: ci-info: +--------+------+--------------+---------------+-------------------+
[   19.748666] cloud-init[766]: ci-info: ++++++++++++++++++++++++++++++++Route info+++++++++++++++++++++++++++++++++
[   19.751774] cloud-init[766]: ci-info: +-------+--------------+--------------+---------------+-----------+-------+
[   19.754839] cloud-init[766]: ci-info: | Route | Destination  |   Gateway    |    Genmask    | Interface | Flags |
[   19.787889] cloud-init[766]: ci-info: +-------+--------------+--------------+---------------+-----------+-------+
[   19.791025] cloud-init[766]: ci-info: |   0   |   0.0.0.0    | 192.168.32.1 |    0.0.0.0    |    eth0   |   UG  |
[   19.794079] cloud-init[766]: ci-info: |   1   | 192.168.32.0 |   0.0.0.0    | 255.255.255.0 |    eth0   |   U   |
[   19.797176] cloud-init[766]: ci-info: +-------+--------------+--------------+---------------+-----------+-------+
[   31.826187] cloud-init[3779]: Cloud-init v. 0.7.5 running 'modules:config' at Thu, 14 Jan 2016 10:40:25 +0000. Up 31.35 seconds.
[   35.154359] cloud-init[3923]: Cloud-init v. 0.7.5 running 'modules:final' at Thu, 14 Jan 2016 10:40:29 +0000. Up 34.84 seconds.
[   35.807138] cloud-init[3923]: Changing password for user root.
[   35.810418] cloud-init[3923]: passwd: all authentication tokens updated successfully.
[   35.932764] cloud-init[3923]: Redirecting to /bin/systemctl restart  sshd.service
[   36.013150] cloud-init[3923]: PING 10.141.255.254 (10.141.255.254) 56(84) bytes of data.
[   36.016043] cloud-init[3923]: 64 bytes from 10.141.255.254: icmp_seq=1 ttl=64 time=0.209 ms
[   36.018705] cloud-init[3923]: --- 10.141.255.254 ping statistics ---
[   36.020979] cloud-init[3923]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
[   36.023627] cloud-init[3923]: rtt min/avg/max/mdev = 0.209/0.209/0.209/0.000 ms
[   38.165255] FS-Cache: Loaded
[   38.202502] FS-Cache: Netfs 'nfs' registered for caching
[   38.278543] Key type dns_resolver registered
[   38.319464] NFS: Registering the id_resolver key type
[   38.321222] Key type id_resolver registered
[   38.322580] Key type id_legacy registered
[   39.395351] cloud-init[3923]: mount -a failed: retrying
[   49.494214] cloud-init[3923]: mount -a failed: retrying
[   59.762825] cloud-init[3923]: mount -a failed: retrying
[   70.015818] cloud-init[3923]: mount -a failed: retrying
[   80.161437] cloud-init[3923]: mount -a failed: retrying
[   90.201173] cloud-init[3923]: mount -a failed: retrying
[  100.238288] cloud-init[3923]: mount -a failed: retrying
[  110.273565] cloud-init[3923]: mount -a failed: retrying
[  120.309587] cloud-init[3923]: mount -a failed: retrying
[  130.346080] cloud-init[3923]: mount -a failed: retrying
[  140.382907] cloud-init[3923]: ERROR: failure to mount file systems.

[  157.330172] cloud-init[3923]: Package nss-pam-ldapd-0.8.13-8.el7.x86_64 already installed and latest version
[  157.351207] cloud-init[3923]: Package authconfig-6.2.8-10.el7.x86_64 already installed and latest version
[  157.354435] cloud-init[3923]: Nothing to do
[  157.463797] cloud-init[3923]: Created symlink from /etc/systemd/system/multi-user.target.wants/slapd.service to /usr/lib/systemd/system/slapd.service.
[  158.210199] cloud-init[3923]: adding new entry "dc=local"
[  158.212610] cloud-init[3923]: adding new entry "ou=People,dc=local"
[  158.214951] cloud-init[3923]: adding new entry "ou=Group,dc=local"
[  158.217219] cloud-init[3923]: adding new entry "cn=uid,dc=local"
[  158.219404] cloud-init[3923]: adding new entry "cn=gid,dc=local"
[  158.668195] cloud-init[3923]: Loaded plugins: fastestmirror
[  158.837181] cloud-init[3923]: Loading mirror speeds from cached hostfile
[  159.180257] cloud-init[3923]: * base: centos.mirror.triple-it.nl
[  159.182730] cloud-init[3923]: * epel: mirror.netcologne.de
[  159.196199] cloud-init[3923]: * extras: mirror.yourwebhoster.eu
[  159.198834] cloud-init[3923]: * updates: mirror.nl.webzilla.com
[  159.911150] cloud-init[3923]: Package nss-pam-ldapd-0.8.13-8.el7.x86_64 already installed and latest version
[  159.925258] cloud-init[3923]: Package authconfig-6.2.8-10.el7.x86_64 already installed and latest version
[  159.928456] cloud-init[3923]: Nothing to do
[  165.738938] cloud-init[3923]: Generating public/private rsa key pair.
[  165.741661] cloud-init[3923]: Your identification has been saved in /root/.ssh/id_rsa.
[  165.744418] cloud-init[3923]: Your public key has been saved in /root/.ssh/id_rsa.pub.
[  165.747043] cloud-init[3923]: The key fingerprint is:
[  165.750581] cloud-init[3923]: eb:1c:2d:22:be:b1:b3:3d:d8:b7:7d:44:31:00:c4:c5 root@login-new
[  165.753535] cloud-init[3923]: The key's randomart image is:
[  165.755655] cloud-init[3923]: +--[ RSA 2048]----+
[  165.757581] cloud-init[3923]: |       oo+o.     |
[  165.759587] cloud-init[3923]: |        . E o    |
[  165.766411] cloud-init[3923]: |             o   |
[  165.768431] cloud-init[3923]: |            .    |
[  165.770465] cloud-init[3923]: |        S  .     |
[  165.772447] cloud-init[3923]: |         o  .    |
[  165.774449] cloud-init[3923]: |    oo. + ..     |
[  165.777481] cloud-init[3923]: |   .o=o+.+  .    |
[  165.779686] cloud-init[3923]: |    =+.o+...     |
[  165.781726] cloud-init[3923]: +-----------------+
[  166.436073] cloud-init[3923]: This account is currently not available.
[  166.530220] cloud-init[3923]: Redirecting to /bin/systemctl restart  munge.service
[  166.811618] cloud-init[3923]: Restarting slurm (via systemctl):  [  OK  ]
ci-info: no authorized ssh keys fingerprints found for user centos.
[  166.851133] cloud-init[3923]: ci-info: no authorized ssh keys fingerprints found for user centos.
ec2: 
ec2: #############################################################
ec2: -----BEGIN SSH HOST KEY FINGERPRINTS-----
ec2: 256 12:67:7d:b5:96:d5:b2:4a:7f:d5:83:dc:07:ce:54:4f   (ECDSA)
ec2: 256 fc:ed:c0:eb:0e:b3:15:6f:7c:9e:5a:92:84:3b:5f:c5   (ED25519)
ec2: 2048 c1:0c:5a:cb:88:89:cb:44:47:35:f1:4e:81:80:d9:50   (RSA)
ec2: -----END SSH HOST KEY FINGERPRINTS-----
ec2: #############################################################
-----BEGIN SSH HOST KEY KEYS-----
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKG2ZJmT0hlgTpI5mGHAdohXXtNGo77aXTjHz+inQP1hacPnJwuLS57cMh67MXFFBhJ2nZTdjIGqxlfdwjDtIHk= 
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILzG6/fbCYqHfpkunSUJJU7yYZGBhjzRivOrezVMQTB4 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIzRAZ10EiKWTdqIzBS9BQmQYl1EKYqdyqiRjwz+oeGIk/Jp1fXF6m2VapSDl4DnqF+zX+GPoX23jdJZkd9J3RbdT9b8sxNdGMog3ZbRwZTPjMsBJ0tHPDpHUV2BWcCMgPDKRvk6GdId9zFAXJiLCEzSD7a2g3nKZSV1X4cUK1UYibpwCPoN0zh1tPLiTLKItLpfpqPzL5TrDhraKE7K4UT1l0rtd2vLZ16u0Yoj2pVKy/1TiMxrHx4U0UcJAic2clZs6Y4u7eDnDkEp0n4nFejMGtDA0xtyYB7DFHgKju8MR+vOPHnCZsJNXuBJvoOJex/KTcSwO96/AvbLLsGMhX 
-----END SSH HOST KEY KEYS-----

```

**Comment by themisa** [comment]
i haven't seen this error in other versions. might have been a fluke.

will close for now.
